# Generated by Django 5.0.4 on 2024-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirketAdi', models.CharField(max_length=100, verbose_name='Şirket Adı')),
                ('sirketTarih', models.DateField(max_length=30, verbose_name='Staj Tarihleri')),
                ('hakkinda', models.TextField(max_length=500, verbose_name='Hakkında')),
                ('resim', models.FileField(blank=True, null=True, upload_to='afis')),
            ],
        ),
    ]
