# Generated by Django 5.0.4 on 2024-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('bolum', models.IntegerField(default=0)),
                ('sinif', models.IntegerField(default=0)),
                ('transkript', models.FloatField(default=0.0)),
                ('konum', models.IntegerField(default=0)),
                ('ingilizce_seviyesi', models.IntegerField(default=0)),
                ('alan', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='sirketTarih',
        ),
        migrations.AddField(
            model_name='company',
            name='alan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='bolum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='ingilizce_seviyesi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='konum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='sinif',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='sirketTarihi',
            field=models.DateField(default='2000-01-01', max_length=30, verbose_name='Staj Tarihleri'),
        ),
        migrations.AddField(
            model_name='company',
            name='transkript',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='hakkinda',
            field=models.TextField(default='', max_length=500, verbose_name='Hakkında'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sirketAdi',
            field=models.CharField(default='', max_length=100, verbose_name='Şirket Adı'),
        ),
    ]
