# Generated by Django 5.0.4 on 2024-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_student_remove_company_sirkettarih_company_alan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alan',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='bolum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='konum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='sirketTarihi',
            field=models.DateField(default='2024-01-01', max_length=30, verbose_name='Staj Tarihleri'),
        ),
    ]
