# Generated by Django 5.0.4 on 2024-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_alan_alter_company_bolum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bolum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='konum',
            field=models.CharField(max_length=30),
        ),
    ]
