# Generated by Django 5.0.4 on 2024-05-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_student_bolum_alter_student_konum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ingilizce_seviyesi',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='alan',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='ingilizce_seviyesi',
            field=models.CharField(max_length=10),
        ),
    ]
