# Generated by Django 5.0.4 on 2024-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_ingilizce_seviyesi_alter_student_alan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hakkinda',
            field=models.TextField(default='', max_length=10000, verbose_name='Hakkında'),
        ),
    ]
