# Generated by Django 5.0.4 on 2024-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_hakkinda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='alan',
            field=models.CharField(max_length=50),
        ),
    ]
