# Generated by Django 5.0.4 on 2024-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_bolum_alter_student_bolum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alan',
            field=models.IntegerField(),
        ),
    ]
